//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_congres
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITE
    {
        public int NUM { get; set; }
        public string LIBELLE { get; set; }
        public Nullable<int> NBPLACES { get; set; }
    }
}
