//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_congres
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGRESSISTE
    {
        public int NUM { get; set; }
        public int NUM_APPARTIENT { get; set; }
        public int NUM_HEBERGE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
    }
}
