//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_congres
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL
    {
        public int NUM { get; set; }
        public string LIBELLE { get; set; }
        public string ADRESSE { get; set; }
        public string VILLE { get; set; }
        public Nullable<int> CP { get; set; }
        public Nullable<int> TEL { get; set; }
        public Nullable<short> ETOILES { get; set; }
        public Nullable<decimal> PRIXCHAMBRE { get; set; }
    }
}
