//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_congres
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdCongresEntities : DbContext
    {
        public BdCongresEntities()
            : base("name=BdCongresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTIVITE> ACTIVITES { get; set; }
        public DbSet<CONGRESSISTE> CONGRESSISTEs { get; set; }
        public DbSet<DATE> DATEs { get; set; }
        public DbSet<DEROULER> DEROULERs { get; set; }
        public DbSet<HOTEL> HOTELS { get; set; }
        public DbSet<INSCRIPTION> INSCRIPTIONs { get; set; }
        public DbSet<INSCRIRE> INSCRIREs { get; set; }
        public DbSet<INTERVENANT> INTERVENANTS { get; set; }
        public DbSet<LIGUE> LIGUES { get; set; }
        public DbSet<SESSION> SESSIONS { get; set; }
        public DbSet<THEME> THEMES { get; set; }
    }
}
