//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_congres
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION
    {
        public int NUM { get; set; }
        public int NUM_PORTE { get; set; }
        public System.DateTime DATEHEURE { get; set; }
        public int NUM_INTERVIENT { get; set; }
        public string NOMINTERVENANT { get; set; }
        public Nullable<int> NBPLACES { get; set; }
        public Nullable<short> SALLE { get; set; }
        public Nullable<decimal> PRIX { get; set; }
    }
}
